title: Mat's GitHub Blog
author: Mat Hollinger
email: hollingm@purdue.edu
description: Mat Hollinger's random blog.

# social links
github_username:  mathollinger # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
